=== Zontzor/enterprise-systems/more-xsd/invoice.xsd
<?xml version="1.0"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.dit.ie"
  xmlns="http://www.dit.ie"
  elementFormDefault="qualified">
  
  <xs:element name="invoice">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="invoicenumber" type="xs:integer"/>
        <xs:element name="invoicedate" type="xs:string"/>
        <xs:element name="invoicetotal" type="xs:integer"/>
        <xs:element name="issuedby" type="xs:string"/>

        <xs:element name="billto">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="address" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="item" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name"/>
              <xs:element name="price"/>
              <xs:element name="quantity"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="paymentinformation" type="xs:string"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Zontzor/enterprise-systems/more-xsd/invoice.xml
<?xml version="1.0"?>
<invoice 
  xmlns="http://www.dit.ie"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="invoice.xsd">
  
  <invoicenumber>1234</invoicenumber>
  <invoicedate>01/03/2017</invoicedate>
  <invoicetotal>600</invoicetotal>
  <issuedby>Bob</issuedby>
  <billto>
    <name>Alex</name>
    <address>123 Fake St.</address>
  </billto>  
  <item>
    <name>Caad 10 Road Bike</name>
    <price>699.99</price>
    <quantity>1</quantity>
  </item>
  <paymentinformation>Visa</paymentinformation>
</invoice>
